spring:
  datasource:
    dynamic:
      enabled: true
      strict: true
      primary: "cds-mysql"

    hikari:
      cds-mysql:
        jdbc-url: jdbc:mysql://192.168.8.43:3306/community_eb_mgr?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: community_eb_mgr
        password: community_eb_mgr
        driver-class-name: com.mysql.cj.jdbc.Driver









