

knife4j:
  enable: true
  setting:
    language: zh_cn


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    # 分组信息也可以在这里配置，在代码的配置类里面配置也是可以的。
    - group: 'user'
      paths-to-match: "/user/**"
      packages-to-scan: "com.suyh.business.controller"

