

spring:
  redis:
    timeout: PT1S
    connect-timeout: PT5S

    host: 192.168.8.43
    port: 6379 # 端口
    password: aiteer
    database: 11
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0


