


#---
#spring:
#  config:
#    activate:
#      on-profile: suyh


eb:
  base:
    token-seconds: 36000
    locales:
      - language: "en"
        country: "US"
      - language: "zh"
        country: "CN"


