
spring:
  flyway:
    enabled: false

community:
  base:
    flyway-cds-mysql:
      enabled: true
      locations:
        - "sqls/mysql"
    flyway-cds-pgsql:
      enabled: true
      locations:
        - "sqls/pgsql"

