

---
spring:
  config:
    activate:
      on-profile: suyh,suyh_dev

  rabbitmq:
    host: "192.168.8.43"
    port: 5672
    username: "admin"
    password: "adminadmin"
    virtual-host: "/suyhHost"
    template:
      exchange: "suyhExchange"
      routing-key: "suyhRoutingKey"
      default-receive-queue: "defaultQueue"


