spring:
  datasource:
    dynamic:
      enabled: true
      strict: true
      primary: "master"

---
spring:
  config:
    activate:
      on-profile: suyh,suyh_mac

biz:
  datasource:
    multi:
      master:
        jdbc-url: jdbc:mysql://isuyh.com:3306/suyh_personal?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: suyh_personal
        password: suyh_personal
        driver-class-name: com.mysql.cj.jdbc.Driver








