# bot相关设置
bot-server:
  # 是否启用telegramBot-server, true/false
  # 如果没有配置，默认为true
  enable: true

  # bot token，通过@botfather获取，一个token只能被一个程序绑定
  token: xxx
  # 指令配置
  # 注意，tgbot指令名只能用下划线连接"_"，使用空格或者其他符号会导致设置指令失败。
  command:
    # 查询余额指令
    balance-command: /balance
    balance-description: "Inquire about account balance."

    # 查询余额的消息结构，格式占位符顺序不能变.银行卡号拼接到最后
    # %.2f是保留两位小数
    balance-message: "Agent Code: %s\r\nThe current balance is: %.2f\r\nThe current payment card is: "

    # 联系客服指令
    contact-command: /contact_customer_service
    contact-description: "Get Customer Service Contact information."
    contact-message: "The following is the customer service contact information:\r\n"
    # 客服列表
    # 如有多个，请依次往下配置
    contact:
      - name: Order Problems Customer Service
        contact-link: "t.me/devjuwurdfsdf2341234001bot"
      - name: Payment Problems Customer Service
        contact-link: "t.me/devtest2"

    # 帮助指令
    help-command: /help
    help-description: "Show help message."
    help-message: "If you have any questions, please contact customer service."

    # start 指令，只返回描述，没有其他作用
    start-command: /start
    start-description: "Welcome to the bot!"

    # 选择收款卡指令
    select-card-command: /select_card
    select-card-description: "Select Payment Card."
    #选择收款卡消息，在该消息下方显示[收款卡号列表]，卡号文本过长是否自动省略是根据这个消息长度来的，实测不要超过4个单词，超过了tg似乎会开启自动省略功能。
    select-card-message: "Please select payment card:"
    # 没有已通过人工审核的收款卡
    select-no-card-message: "No payment card found."

    # 选择成功消息
    select-card-success-message: "Setup successful!!!"
    # 选择失败消息
    select-card-fail-message: "Failed to select payment card, please contact customer service"

    # 未知指令回复消息
    unknown-command-message: "Unknown command."

    # username没有绑定Code回复消息
    no-bind-code-message: "Please bind your code first. \r\nIf you need help, please contact customer service."


---
spring:
  config:
    activate:
      on-profile: suyh

# bot相关设置
bot-server:
  # bot token，通过@botfather获取
  token: 7109132055:AAHt2e0l5sBhZXnfwzKB6JRPyyuSrCcF2MM


---
spring:
  config:
    activate:
      on-profile: suyh_dev

# bot相关设置
bot-server:
  # bot token，通过@botfather获取
  token: 7530223963:AAE8D-S5EGNo9otioEK5OIP1OpzavN5zf6s

---
spring:
  config:
    activate:
      on-profile: dev

# bot相关设置
bot-server:
  # bot token，通过@botfather获取
  token: 7229193059:AAGBPqrwbMIaQUgrmKRHoSdcB7JsheEnWmY

---
spring:
  config:
    activate:
      on-profile: wtdev

# bot相关设置
bot-server:
  # bot token，通过@botfather获取, 一个token只能被一个程序绑定
  token: 7407855801:AAEjzEQt7RKCC2X6j-dR4do_YnywOdqgatY


