
spring:
  flyway:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: suyh

community:
  base:
    flyway-cds-mysql:
      enabled: true
      locations:
        - "sqls/mysql"
    flyway-cds-pgsql:
      enabled: false
      locations:
        - "sqls/pgsql"

